# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Add the pods for the Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod ‘Firebase/Database’
pod ‘FirebaseFirestoreSwift’
pod 'Firebase/Storage'
target 'Project 1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod ‘Firebase/Database’
	pod ‘FirebaseFirestoreSwift'
	pod 'Firebase/Storage'
  # Pods for Project 1

end
